//! Identity monitoring and security alerting.
//!
//! Provides an `IdentityWatcher` that tracks on-chain identity events and
//! generates security alerts for suspicious activity. Designed to integrate
//! with event subscription systems (e.g., ethers-rs, alloy) in production.
//!
//! # Event Types Monitored
//!
//! - `RecoveryStateChanged` — identity entering/leaving recovery
//! - `DelegationEndorsed` — new delegation certificates issued
//! - `SessionInvalidated` — mass session cancellation
//! - `IntentExecuted` — execution events for audit trail

/// Severity level for security alerts.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlertSeverity {
    /// Informational — routine protocol operations.
    Info,
    /// Warning — unusual but potentially legitimate activity.
    Warning,
    /// Critical — immediate attention required (e.g., unknown guardian recovery).
    Critical,
}

/// A security alert generated by the identity watcher.
#[derive(Debug, Clone)]
pub struct SecurityAlert {
    /// Severity level of the alert.
    pub severity: AlertSeverity,
    /// Alert category identifier.
    pub category: AlertCategory,
    /// Human-readable description of the alert.
    pub message: String,
    /// The identity (root address) this alert relates to.
    pub identity: [u8; 20],
    /// Block number where the event occurred (0 if off-chain).
    pub block_number: u64,
    /// Unix timestamp of the alert.
    pub timestamp: u64,
}

/// Categories of security alerts.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlertCategory {
    /// Recovery initiated by a guardian.
    RecoveryInitiated,
    /// Recovery finalized — identity transferred.
    RecoveryFinalized,
    /// Recovery cancelled by the original root.
    RecoveryCancelled,
    /// Identity frozen.
    IdentityFrozen,
    /// Identity unfrozen.
    IdentityUnfrozen,
    /// New delegation certificate endorsed.
    DelegationIssued,
    /// Unknown or unauthorized delegation detected.
    UnknownDelegation,
    /// All sessions cancelled (mass invalidation).
    SessionsInvalidated,
    /// Execution event recorded.
    ExecutionRecorded,
    /// Off-chain session issuance detected without on-chain registration.
    OfflineSessionDetected,
    /// High-value intent executed above configured threshold.
    HighValueIntent,
}

/// A notification destined for a specific guardian.
#[derive(Debug, Clone)]
pub struct GuardianNotification {
    /// The guardian address this notification targets.
    pub guardian: [u8; 20],
    /// The security alert that triggered the notification.
    pub alert: SecurityAlert,
}

/// Configuration for the identity watcher.
#[derive(Debug, Clone)]
pub struct WatcherConfig {
    /// Wei threshold above which intent execution triggers a high-value alert.
    /// Set to 0 to disable high-value alerts.
    pub high_value_threshold: u128,
}

/// Tracks identity events and generates security alerts.
///
/// In production, this would subscribe to Ethereum events via a provider
/// (ethers-rs / alloy). This implementation provides the core alert logic
/// that can be driven by any event source.
pub struct IdentityWatcher {
    /// Known authorized guardians for each identity.
    known_guardians: Vec<([u8; 20], Vec<[u8; 20]>)>,
    /// Known authorized delegates for each identity.
    known_delegates: Vec<([u8; 20], Vec<[u8; 20]>)>,
    /// Alert log.
    alerts: Vec<SecurityAlert>,
    /// Pending guardian notifications (drained by consumers).
    pending_notifications: Vec<GuardianNotification>,
    /// Watcher configuration.
    config: WatcherConfig,
    /// Structured event log (black box) for all protocol activity.
    event_log: EventLog,
}

impl IdentityWatcher {
    /// Create a new identity watcher with default configuration.
    pub fn new() -> Self {
        Self {
            known_guardians: Vec::new(),
            known_delegates: Vec::new(),
            alerts: Vec::new(),
            pending_notifications: Vec::new(),
            config: WatcherConfig {
                high_value_threshold: 0,
            },
            event_log: EventLog::new(),
        }
    }

    /// Create a new identity watcher with the given configuration.
    pub fn with_config(config: WatcherConfig) -> Self {
        Self {
            known_guardians: Vec::new(),
            known_delegates: Vec::new(),
            alerts: Vec::new(),
            pending_notifications: Vec::new(),
            config,
            event_log: EventLog::new(),
        }
    }

    /// Register known guardians for an identity.
    pub fn register_guardians(&mut self, identity: [u8; 20], guardians: Vec<[u8; 20]>) {
        self.known_guardians.push((identity, guardians));
    }

    /// Register a known delegate for an identity.
    pub fn register_delegate(&mut self, identity: [u8; 20], delegate: [u8; 20]) {
        if let Some(entry) = self.known_delegates.iter_mut().find(|(id, _)| *id == identity) {
            entry.1.push(delegate);
        } else {
            self.known_delegates.push((identity, vec![delegate]));
        }
    }

    /// Process a `RecoveryStateChanged` event.
    ///
    /// Generates a Critical alert if recovery is initiated by an unknown guardian,
    /// or a Warning if by a known guardian (since it may still be unauthorized).
    pub fn on_recovery_state_changed(
        &mut self,
        identity: [u8; 20],
        new_state: &str,
        guardian: Option<[u8; 20]>,
        block_number: u64,
        timestamp: u64,
    ) -> SecurityAlert {
        let (severity, category, message) = match new_state {
            "RecoveryPending" => {
                let is_known = guardian.map_or(false, |g| self.is_known_guardian(&identity, &g));
                if is_known {
                    (
                        AlertSeverity::Warning,
                        AlertCategory::RecoveryInitiated,
                        format!(
                            "Recovery initiated by known guardian 0x{} for identity 0x{}",
                            guardian.map_or_else(|| "unknown".to_string(), |g| hex::encode(g)),
                            hex::encode(identity)
                        ),
                    )
                } else {
                    (
                        AlertSeverity::Critical,
                        AlertCategory::RecoveryInitiated,
                        format!(
                            "CRITICAL: Recovery initiated by UNKNOWN guardian 0x{} for identity 0x{}",
                            guardian.map_or_else(|| "unknown".to_string(), |g| hex::encode(g)),
                            hex::encode(identity)
                        ),
                    )
                }
            }
            "Active" => (
                AlertSeverity::Info,
                AlertCategory::RecoveryCancelled,
                format!("Recovery cancelled/finalized for identity 0x{}", hex::encode(identity)),
            ),
            "Frozen" => (
                AlertSeverity::Warning,
                AlertCategory::IdentityFrozen,
                format!("Identity 0x{} has been FROZEN", hex::encode(identity)),
            ),
            _ => (
                AlertSeverity::Info,
                AlertCategory::RecoveryCancelled,
                format!("Identity state changed to {} for 0x{}", new_state, hex::encode(identity)),
            ),
        };

        let alert = SecurityAlert {
            severity,
            category,
            message,
            identity,
            block_number,
            timestamp,
        };

        self.alerts.push(alert.clone());
        self.event_log.record_recovery_state_changed(identity, new_state, guardian, block_number, timestamp);

        // Notify guardians for any recovery or freeze event
        if matches!(alert.severity, AlertSeverity::Warning | AlertSeverity::Critical) {
            self.notify_guardians(&identity, &alert);
        }

        alert
    }

    /// Process a `DelegationEndorsed` event.
    ///
    /// Generates a Warning if the delegate is unknown, Info if known.
    pub fn on_delegation_endorsed(
        &mut self,
        identity: [u8; 20],
        delegate: [u8; 20],
        scope: [u8; 4],
        block_number: u64,
        timestamp: u64,
    ) -> SecurityAlert {
        let is_known = self.is_known_delegate(&identity, &delegate);

        let (severity, category) = if is_known {
            (AlertSeverity::Info, AlertCategory::DelegationIssued)
        } else {
            (AlertSeverity::Warning, AlertCategory::UnknownDelegation)
        };

        let alert = SecurityAlert {
            severity,
            category,
            message: format!(
                "Delegation endorsed: delegate=0x{} scope=0x{} identity=0x{} known={}",
                hex::encode(delegate),
                hex::encode(scope),
                hex::encode(identity),
                is_known,
            ),
            identity,
            block_number,
            timestamp,
        };

        self.alerts.push(alert.clone());
        alert
    }

    /// Process a `SessionInvalidated` event.
    pub fn on_session_invalidated(
        &mut self,
        identity: [u8; 20],
        new_epoch: u64,
        block_number: u64,
        timestamp: u64,
    ) -> SecurityAlert {
        let alert = SecurityAlert {
            severity: AlertSeverity::Warning,
            category: AlertCategory::SessionsInvalidated,
            message: format!(
                "All sessions cancelled for identity 0x{}. New epoch: {}",
                hex::encode(identity),
                new_epoch,
            ),
            identity,
            block_number,
            timestamp,
        };

        self.alerts.push(alert.clone());
        self.event_log.record_session_invalidated(identity, new_epoch, block_number, timestamp);
        alert
    }

    /// Process an `IntentExecuted` event.
    pub fn on_intent_executed(
        &mut self,
        identity: [u8; 20],
        session_key: [u8; 20],
        selector: [u8; 4],
        block_number: u64,
        timestamp: u64,
    ) -> SecurityAlert {
        let alert = SecurityAlert {
            severity: AlertSeverity::Info,
            category: AlertCategory::ExecutionRecorded,
            message: format!(
                "Intent executed: session=0x{} selector=0x{} identity=0x{}",
                hex::encode(session_key),
                hex::encode(selector),
                hex::encode(identity),
            ),
            identity,
            block_number,
            timestamp,
        };

        self.alerts.push(alert.clone());
        self.event_log.record_intent_executed(identity, session_key, selector, block_number, timestamp);
        alert
    }

    /// Detect off-chain session issuance by checking if a session key was
    /// used on-chain without prior registration. Called when an execution
    /// event references an unknown session key.
    pub fn on_offline_session_detected(
        &mut self,
        identity: [u8; 20],
        session_key: [u8; 20],
        block_number: u64,
        timestamp: u64,
    ) -> SecurityAlert {
        let alert = SecurityAlert {
            severity: AlertSeverity::Critical,
            category: AlertCategory::OfflineSessionDetected,
            message: format!(
                "CRITICAL: Offline session key detected: session=0x{} identity=0x{}. \
                 Session was used without prior on-chain registration.",
                hex::encode(session_key),
                hex::encode(identity),
            ),
            identity,
            block_number,
            timestamp,
        };

        self.alerts.push(alert.clone());
        alert
    }

    /// Process a high-value intent execution event.
    ///
    /// Generates a Warning alert if the intent value exceeds the configured threshold.
    /// Also triggers guardian notifications for the identity's known guardians.
    pub fn on_high_value_intent(
        &mut self,
        identity: [u8; 20],
        session_key: [u8; 20],
        value: u128,
        selector: [u8; 4],
        block_number: u64,
        timestamp: u64,
    ) -> Option<SecurityAlert> {
        if self.config.high_value_threshold == 0 || value < self.config.high_value_threshold {
            return None;
        }

        let alert = SecurityAlert {
            severity: AlertSeverity::Warning,
            category: AlertCategory::HighValueIntent,
            message: format!(
                "High-value intent executed: session=0x{} selector=0x{} value={} wei identity=0x{}",
                hex::encode(session_key),
                hex::encode(selector),
                value,
                hex::encode(identity),
            ),
            identity,
            block_number,
            timestamp,
        };

        self.alerts.push(alert.clone());
        self.event_log.record_high_value_intent(identity, session_key, value, selector, block_number, timestamp);
        self.notify_guardians(&identity, &alert);
        Some(alert)
    }

    /// Notify all known guardians for an identity about a security alert.
    fn notify_guardians(&mut self, identity: &[u8; 20], alert: &SecurityAlert) {
        let guardians: Vec<[u8; 20]> = self
            .known_guardians
            .iter()
            .filter(|(id, _)| id == identity)
            .flat_map(|(_, gs)| gs.clone())
            .collect();

        for guardian in guardians {
            self.pending_notifications.push(GuardianNotification {
                guardian,
                alert: alert.clone(),
            });
        }
    }

    /// Drain all pending guardian notifications.
    ///
    /// Returns all accumulated notifications and clears the internal queue.
    /// In production, a consumer (e.g., push notification service, webhook dispatcher)
    /// calls this periodically to deliver alerts to guardians.
    pub fn drain_notifications(&mut self) -> Vec<GuardianNotification> {
        std::mem::take(&mut self.pending_notifications)
    }

    /// Get all alerts generated so far.
    pub fn alerts(&self) -> &[SecurityAlert] {
        &self.alerts
    }

    /// Get alerts filtered by severity.
    pub fn alerts_by_severity(&self, severity: AlertSeverity) -> Vec<&SecurityAlert> {
        self.alerts.iter().filter(|a| a.severity == severity).collect()
    }

    /// Get alerts for a specific identity.
    pub fn alerts_for_identity(&self, identity: &[u8; 20]) -> Vec<&SecurityAlert> {
        self.alerts.iter().filter(|a| &a.identity == identity).collect()
    }

    /// Clear all alerts.
    pub fn clear_alerts(&mut self) {
        self.alerts.clear();
    }

    /// Access the structured event log (black box).
    pub fn event_log(&self) -> &EventLog {
        &self.event_log
    }

    /// Get a mutable reference to the event log.
    pub fn event_log_mut(&mut self) -> &mut EventLog {
        &mut self.event_log
    }

    fn is_known_guardian(&self, identity: &[u8; 20], guardian: &[u8; 20]) -> bool {
        self.known_guardians
            .iter()
            .any(|(id, gs)| id == identity && gs.contains(guardian))
    }

    fn is_known_delegate(&self, identity: &[u8; 20], delegate: &[u8; 20]) -> bool {
        self.known_delegates
            .iter()
            .any(|(id, ds)| id == identity && ds.contains(delegate))
    }
}

impl Default for IdentityWatcher {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Event Log — Structured Black Box for Identity History
// ---------------------------------------------------------------------------

/// A single structured event entry in the identity event log.
#[derive(Debug, Clone)]
pub struct EventLogEntry {
    /// Event type identifier.
    pub event_type: EventType,
    /// The identity (root address) this event relates to.
    pub identity: [u8; 20],
    /// Block number where the event occurred.
    pub block_number: u64,
    /// Unix timestamp of the event.
    pub timestamp: u64,
    /// Event-specific metadata as key-value pairs.
    pub metadata: Vec<(String, String)>,
}

/// Types of events recorded in the event log.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventType {
    /// An intent was executed on-chain.
    IntentExecuted,
    /// All sessions were invalidated (epoch incremented).
    SessionInvalidated,
    /// Recovery state changed.
    RecoveryStateChanged,
    /// Delegation endorsed.
    DelegationEndorsed,
    /// High-value intent detected.
    HighValueIntent,
}

/// Structured event log for recording all protocol activity.
///
/// Serves as the "black box" — a complete, append-only history of every
/// identity event observed by the watcher. Can be exported to JSON for
/// dashboard consumption or forensic analysis.
pub struct EventLog {
    entries: Vec<EventLogEntry>,
}

impl EventLog {
    /// Create a new empty event log.
    pub fn new() -> Self {
        Self {
            entries: Vec::new(),
        }
    }

    /// Append an event to the log.
    pub fn record(&mut self, entry: EventLogEntry) {
        self.entries.push(entry);
    }

    /// Record an IntentExecuted event.
    pub fn record_intent_executed(
        &mut self,
        identity: [u8; 20],
        session_key: [u8; 20],
        selector: [u8; 4],
        block_number: u64,
        timestamp: u64,
    ) {
        self.record(EventLogEntry {
            event_type: EventType::IntentExecuted,
            identity,
            block_number,
            timestamp,
            metadata: vec![
                ("session_key".into(), format!("0x{}", hex::encode(session_key))),
                ("selector".into(), format!("0x{}", hex::encode(selector))),
            ],
        });
    }

    /// Record a SessionInvalidated event.
    pub fn record_session_invalidated(
        &mut self,
        identity: [u8; 20],
        new_epoch: u64,
        block_number: u64,
        timestamp: u64,
    ) {
        self.record(EventLogEntry {
            event_type: EventType::SessionInvalidated,
            identity,
            block_number,
            timestamp,
            metadata: vec![
                ("new_epoch".into(), new_epoch.to_string()),
            ],
        });
    }

    /// Record a RecoveryStateChanged event.
    pub fn record_recovery_state_changed(
        &mut self,
        identity: [u8; 20],
        new_state: &str,
        guardian: Option<[u8; 20]>,
        block_number: u64,
        timestamp: u64,
    ) {
        let mut meta = vec![
            ("new_state".into(), new_state.to_string()),
        ];
        if let Some(g) = guardian {
            meta.push(("guardian".into(), format!("0x{}", hex::encode(g))));
        }
        self.record(EventLogEntry {
            event_type: EventType::RecoveryStateChanged,
            identity,
            block_number,
            timestamp,
            metadata: meta,
        });
    }

    /// Record a HighValueIntent event.
    pub fn record_high_value_intent(
        &mut self,
        identity: [u8; 20],
        session_key: [u8; 20],
        value: u128,
        selector: [u8; 4],
        block_number: u64,
        timestamp: u64,
    ) {
        self.record(EventLogEntry {
            event_type: EventType::HighValueIntent,
            identity,
            block_number,
            timestamp,
            metadata: vec![
                ("session_key".into(), format!("0x{}", hex::encode(session_key))),
                ("selector".into(), format!("0x{}", hex::encode(selector))),
                ("value_wei".into(), value.to_string()),
            ],
        });
    }

    /// Get all entries in the log.
    pub fn entries(&self) -> &[EventLogEntry] {
        &self.entries
    }

    /// Get entries filtered by event type.
    pub fn entries_by_type(&self, event_type: EventType) -> Vec<&EventLogEntry> {
        self.entries.iter().filter(|e| e.event_type == event_type).collect()
    }

    /// Get entries for a specific identity.
    pub fn entries_for_identity(&self, identity: &[u8; 20]) -> Vec<&EventLogEntry> {
        self.entries.iter().filter(|e| &e.identity == identity).collect()
    }

    /// Export the entire log as a JSON string.
    ///
    /// Each entry is serialized with its event type, identity, block number,
    /// timestamp, and metadata key-value pairs.
    pub fn export_json(&self) -> String {
        let mut json = String::from("[\n");
        for (i, entry) in self.entries.iter().enumerate() {
            if i > 0 {
                json.push_str(",\n");
            }
            json.push_str("  {\n");
            json.push_str(&format!("    \"event_type\": \"{:?}\",\n", entry.event_type));
            json.push_str(&format!("    \"identity\": \"0x{}\",\n", hex::encode(entry.identity)));
            json.push_str(&format!("    \"block_number\": {},\n", entry.block_number));
            json.push_str(&format!("    \"timestamp\": {},\n", entry.timestamp));
            json.push_str("    \"metadata\": {");
            for (j, (key, val)) in entry.metadata.iter().enumerate() {
                if j > 0 {
                    json.push(',');
                }
                json.push_str(&format!("\n      \"{}\": \"{}\"", key, val));
            }
            json.push_str("\n    }\n  }");
        }
        json.push_str("\n]");
        json
    }

    /// Get the total number of recorded events.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Check if the log is empty.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Clear all entries.
    pub fn clear(&mut self) {
        self.entries.clear();
    }
}

impl Default for EventLog {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Dashboard State — Aggregated Protocol Metrics
// ---------------------------------------------------------------------------

/// A snapshot of aggregated protocol metrics at a point in time.
#[derive(Debug, Clone)]
pub struct DashboardSnapshot {
    /// Number of unique identities with recorded events.
    pub active_identities: usize,
    /// Number of identities currently in RecoveryPending state.
    pub pending_recoveries: usize,
    /// Total number of intents executed.
    pub executed_intents: usize,
    /// Number of high-value intents detected.
    pub high_value_intents: usize,
    /// Number of session epoch revocations (mass invalidations).
    pub revoked_sessions: usize,
    /// Unix timestamp when the snapshot was generated.
    pub snapshot_timestamp: u64,
}

/// Aggregated dashboard state computed from the event log.
pub struct DashboardState<'a> {
    event_log: &'a EventLog,
}

impl<'a> DashboardState<'a> {
    /// Create a new DashboardState from an event log reference.
    pub fn new(event_log: &'a EventLog) -> Self {
        Self { event_log }
    }

    /// Generate a snapshot of the current dashboard metrics.
    pub fn snapshot(&self, timestamp: u64) -> DashboardSnapshot {
        let entries = self.event_log.entries();

        let mut identities = std::collections::HashSet::new();
        let mut pending_recoveries = 0usize;
        let mut executed_intents = 0usize;
        let mut high_value_intents = 0usize;
        let mut revoked_sessions = 0usize;

        for entry in entries {
            identities.insert(entry.identity);
            match entry.event_type {
                EventType::IntentExecuted => executed_intents += 1,
                EventType::HighValueIntent => high_value_intents += 1,
                EventType::SessionInvalidated => revoked_sessions += 1,
                EventType::RecoveryStateChanged => {
                    // Count entries where new_state is "RecoveryPending"
                    if entry.metadata.iter().any(|(k, v)| k == "new_state" && v == "RecoveryPending") {
                        pending_recoveries += 1;
                    }
                }
                _ => {}
            }
        }

        DashboardSnapshot {
            active_identities: identities.len(),
            pending_recoveries,
            executed_intents,
            high_value_intents,
            revoked_sessions,
            snapshot_timestamp: timestamp,
        }
    }

    /// Generate a snapshot filtered to a specific time range.
    pub fn snapshot_in_range(&self, from: u64, to: u64, snapshot_timestamp: u64) -> DashboardSnapshot {
        let entries = self.event_log.entries();

        let mut identities = std::collections::HashSet::new();
        let mut pending_recoveries = 0usize;
        let mut executed_intents = 0usize;
        let mut high_value_intents = 0usize;
        let mut revoked_sessions = 0usize;

        for entry in entries {
            if entry.timestamp < from || entry.timestamp > to {
                continue;
            }
            identities.insert(entry.identity);
            match entry.event_type {
                EventType::IntentExecuted => executed_intents += 1,
                EventType::HighValueIntent => high_value_intents += 1,
                EventType::SessionInvalidated => revoked_sessions += 1,
                EventType::RecoveryStateChanged => {
                    if entry.metadata.iter().any(|(k, v)| k == "new_state" && v == "RecoveryPending") {
                        pending_recoveries += 1;
                    }
                }
                _ => {}
            }
        }

        DashboardSnapshot {
            active_identities: identities.len(),
            pending_recoveries,
            executed_intents,
            high_value_intents,
            revoked_sessions,
            snapshot_timestamp,
        }
    }

    /// Filter entries by identity.
    pub fn entries_for_identity(&self, identity: &[u8; 20]) -> Vec<&EventLogEntry> {
        self.event_log.entries_for_identity(identity)
    }

    /// Filter entries by event type.
    pub fn entries_by_type(&self, event_type: EventType) -> Vec<&EventLogEntry> {
        self.event_log.entries_by_type(event_type)
    }

    /// Filter entries by time range.
    pub fn entries_in_range(&self, from: u64, to: u64) -> Vec<&EventLogEntry> {
        self.event_log.entries().iter()
            .filter(|e| e.timestamp >= from && e.timestamp <= to)
            .collect()
    }

    /// Export the dashboard snapshot as a JSON string.
    pub fn export_json(&self, timestamp: u64) -> String {
        let snap = self.snapshot(timestamp);
        format!(
            concat!(
                "{{\n",
                "  \"active_identities\": {},\n",
                "  \"pending_recoveries\": {},\n",
                "  \"executed_intents\": {},\n",
                "  \"high_value_intents\": {},\n",
                "  \"revoked_sessions\": {},\n",
                "  \"snapshot_timestamp\": {}\n",
                "}}"
            ),
            snap.active_identities,
            snap.pending_recoveries,
            snap.executed_intents,
            snap.high_value_intents,
            snap.revoked_sessions,
            snap.snapshot_timestamp,
        )
    }
}

/// Convenience function: generate a dashboard state JSON from an EventLog.
pub fn export_dashboard_state(event_log: &EventLog, timestamp: u64) -> String {
    DashboardState::new(event_log).export_json(timestamp)
}
